# Generated by Django 3.0.3 on 2020-03-03 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myConnections', '0002_auto_20200303_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to=settings.AUTH_USER_MODEL),
        ),
    ]
